name: Fastq Test (DinD)

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    # 使用DinD配置
    runs-on: ubuntu-latest  # 必须用ubuntu-latest，docker运行器已弃用
    container:
      image: docker:24.0-dind  # 使用新版DinD镜像
      options: --privileged --network=host

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # --- 初始化 ---
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        if: github.event_name != 'pull_request'
        run: |
          wget https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign-linux-amd64
          chmod +x cosign-linux-amd64
          mv cosign-linux-amd64 /usr/local/bin/cosign

      # --- 构建阶段 ---
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} \
            -u ${{ github.actor }} \
            --password-stdin

      - name: Build and push
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            .
          
          if [ "${{ github.event_name }}" != "pull_request" ]; then
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          fi

      - name: Sign image
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cosign sign --yes ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cosign sign --yes ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      # --- 测试阶段 ---
      - name: Download test data
        run: |
          apk add --no-cache wget
          mkdir -p test_data
          wget -O test_data/test_R1.fastq.gz https://zenodo.org/record/3736457/files/ERR011347_1.fastq.gz
          wget -O test_data/test_R2.fastq.gz https://zenodo.org/record/3736457/files/ERR011347_2.fastq.gz

      - name: Run test
        run: |
          mkdir -p output
          docker run --rm \
            -v $(pwd)/test_data:/mnt/in \
            -v $(pwd)/output:/mnt/out \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Verify outputs
        run: |
          test -f output/test_trimmed_R1.fastq.gz || (echo "Missing R1 output"; exit 1)
          test -f output/test_fastp.html || (echo "Missing HTML report"; exit 1)
